# Generated by Django 2.1.1 on 2018-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='описание',
        ),
        migrations.AddField(
            model_name='product',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
