# Generated by Django 2.1.2 on 2018-10-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181004_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
        ),
    ]
