# Generated by Django 2.1.2 on 2018-10-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20181004_1918'),
        ('products', '0006_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='images.Image'),
            preserve_default=False,
        ),
    ]
